language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
script:
- bundle exec rake default
- gem build sensu-plugins-inspec.gemspec
- gem install sensu-plugins-inspec-*.gem