language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.4.1
script:
- bundle exec rake default
- gem build sensu-plugins-inspec.gemspec
- gem install sensu-plugins-inspec-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-inspec
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
env:
  global:
    secure: g5STbujBidWFI1Mj+dnoMGpPJvcMmKPdPeML/XUMxY9uoJm82FstvXqSUaT8W+xAgfzjTZL7F+bf6OeJzYswkDLz8t4YQMpnPnFZEavcdzaezBr8Dz+ysTvykY6qLTvOa67E1525Wea1VOspdoK4WNKptZ93o4xbk2L0YOYpDX83zO3AgzqvfPIwLNdog5548OceUrqPCbhLKJmLg5p0fyRL1jPrP3YSZ581GhlFpGegkw+aQ36+JJ2rprimM1fBPskeQI+3fQADIxF/IqwIfLsjDWDnYyjlKly4Jc9laVq2JVr0msMS6NcuVRcH6fGK0VShssne20VJwaQEqEJyiZ3ldqvvOT8AwhAxi+318nFUNnLfUougdhE6cQogmLxQkDhqEQpj/OmpXwQg0weRQhp4ekICPgTMRYLqQqfVuklCwXbd1DYmFWKDLgIpZVOtlPt0nfiXiN8IdFMW8ROemwkPm+igcz7WzHL88GJMjjwnVsadsp3hvsWRWP/2SeEFW5sS5437mIPGh9V8aPl6omqTiWQPWnGwOuUkz/zLrtDXkSG241eq/8Ay/j0QE1DISshWjmRPm2quo6BL+cyJUVE7NDnYgXIDSqcvyEbXlV64LDeFFoY11tqJD6FK+I4lnWxOM/HsIkboz56HkppVr6P3yJrwRANvJDyAdmtIVfE=
